### ISSUE TITLE
seagulf.glb is an invalid glb file.

### ISSUE THREAD

**Issue by vpenades** [BabylonJS/MeshesLibrary#23]
I'm using MeshesLibrary repository for unit testing, and I've found that seagulf.glb model is invalid.

The reason is that it has BufferViews defined as GPU Ready Vertex Buffers which also contains images.

This has been confirmed with glTF validator.

Please, fix the model, or remove it altogether.

**Comment by deltakosh** [comment]
Pinging @bghgary
