### ISSUE TITLE
Cornell Box

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/MeshesLibrary#4]
Are you interested for me pushing [cornell box scene](https://github.com/Vinc3r/cornellBox) here? If yes, should have I to push the `.blend` file too, or only `.gtlf` and `.babylon` are interesting for this repo? (`.babylon` version is not yet ready by the way)

**Comment by deltakosh** [comment]
Blend and glb coukd be great!

**Comment by Vinc3r** [comment]
Ok I will PR this in few days, I close issue for now.
